// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZHm8OW_VCEOrs8mUf3wvsf-4bD4sHHjA',
    appId: '1:804595808883:web:6691b6b4fa2d9ad4930806',
    messagingSenderId: '804595808883',
    projectId: 'controle-abastecimento-c6f62',
    authDomain: 'controle-abastecimento-c6f62.firebaseapp.com',
    storageBucket: 'controle-abastecimento-c6f62.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeRY5iZ72YQxut6AZoFkYkfJB1Ghew5Lk',
    appId: '1:804595808883:android:eae6477618b6bd88930806',
    messagingSenderId: '804595808883',
    projectId: 'controle-abastecimento-c6f62',
    storageBucket: 'controle-abastecimento-c6f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbu8RFswE0CSMhU79AteSSJSDrmHWLIk',
    appId: '1:804595808883:ios:6d0e1e752a341fce930806',
    messagingSenderId: '804595808883',
    projectId: 'controle-abastecimento-c6f62',
    storageBucket: 'controle-abastecimento-c6f62.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
